### ISSUE TITLE
Study linked-data-creator-api

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/linked-data-creator-api#1]
@Connoropolous  wanted you to know that this sounds really interesting, and I'm happy you put it here.  Want to study what you have done, and understand better how it fits in, but haven't gotten to it yet.  Will do so when I get enough head space to think about it, hopefully soon!  :smile:

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-creator-api/-/issues/1.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
