### ISSUE TITLE
linked data graph database instead of mongodb

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/linked-data-creator-api#2]
instead of mongodb, i reckon it'd be better for us to use a database more suited for linked data graphs.

my recommendation is [levelgraph-jsonld](https://github.com/mcollina/levelgraph-jsonld), as it's built on the [levelup](https://github.com/level/levelup) and [levelgraph](https://github.com/mcollina/levelgraph) ecosystems, where the philosophy is ["build your own database" based on your needs instead of "batteries included"](https://mcollina.github.io/levelup-talk-cloudconf/).

there's also more options for linked data graph databases:
- https://github.com/uf6/design/issues/5.
- https://github.com/uf6/design/issues/3

**Comment by Connoropolous** [comment]
@bortseb I recommend checking out this presentation that Mikey linked to above 
https://mcollina.github.io/levelup-talk-cloudconf/

**Comment by Connoropolous** [comment]
thanks Mikey, that's very interesting! it would certainly appear to make a lot more sense than mongo

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-creator-api/-/issues/2.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
