### ISSUE TITLE
federated queries

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/linked-data-creator-api#3]
i'm not sure if this is part of `linked-data-creator-api`, or if it's a separate layer above, but anyways it was mentioned and it's awesome so i'll share some thoughts here:

the best approach for this that i've seen is [Linked Data Fragments](http://linkeddatafragments.org/). they even have a [Node.js server implementation](https://github.com/LinkedDataFragments/Server.js) that we could use.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/linked-data-creator-api/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
